<?php

use Hard2Code\Entity\Picture\ArrayPictureImpl;

return [
    new ArrayPictureImpl([
        "ID"                  => "1938",
        "TIMESTAMP_X"         => "11.07.2023 12:04:49",
        "MODULE_ID"           => "iblock",
        "HEIGHT"              => 1000,
        "WIDTH"               => 1000,
        "FILE_SIZE"           => "144729",
        "CONTENT_TYPE"        => "image/png",
        "SUBDIR"              => "iblock/b98",
        "FILE_NAME"           => "atd776hhknvaqqmqp0fs03qc2jr4skx9.png",
        "ORIGINAL_NAME"       => "full_zacs_09_hpf_a17_n1_perfecto_5000x5000.png",
        "DESCRIPTION"         => "",
        "HANDLER_ID"          => null,
        "EXTERNAL_ID"         => "0c9621760459c49aef1832e73b902eb1",
        "VERSION_ORIGINAL_ID" => "",
        "META"                => "",
        "SRC"                 => "/upload/iblock/b98/atd776hhknvaqqmqp0fs03qc2jr4skx9.png",
    ]),

    new ArrayPictureImpl([
        "ID"                  => "1939",
        "TIMESTAMP_X"         => "11.07.2023 12:04:49",
        "MODULE_ID"           => "iblock",
        "HEIGHT"              => 1000,
        "WIDTH"               => 1000,
        "FILE_SIZE"           => "274647",
        "CONTENT_TYPE"        => "image/png",
        "SUBDIR"              => "iblock/769",
        "FILE_NAME"           => "5vlfc8lo5fbocewithly9scihtahossu.png",
        "ORIGINAL_NAME"       => "full_zanussi_2500x2500_perfecto.png",
        "DESCRIPTION"         => "",
        "HANDLER_ID"          => null,
        "EXTERNAL_ID"         => "4c399ca8d57e802c037405a95b26a955",
        "VERSION_ORIGINAL_ID" => "",
        "META"                => "",
        "SRC"                 => "/upload/iblock/769/5vlfc8lo5fbocewithly9scihtahossu.png",
    ]),

    new ArrayPictureImpl([
        "ID"                  => "1940",
        "TIMESTAMP_X"         => "11.07.2023 12:04:49",
        "MODULE_ID"           => "iblock",
        "HEIGHT"              => 1000,
        "WIDTH"               => 1000,
        "FILE_SIZE"           => "323791",
        "CONTENT_TYPE"        => "image/png",
        "SUBDIR"              => "iblock/6c5",
        "FILE_NAME"           => "epe1nynjbotdkmciael1aqirr7h28oxc.png",
        "ORIGINAL_NAME"       => "full_zacs_07_hpf_a17_n1_in_184394_004_1.png",
        "DESCRIPTION"         => "",
        "HANDLER_ID"          => null,
        "EXTERNAL_ID"         => "4ef0085bb7b2d2d09449940b261d3ce0",
        "VERSION_ORIGINAL_ID" => "",
        "META"                => "",
        "SRC"                 => "/upload/iblock/6c5/epe1nynjbotdkmciael1aqirr7h28oxc.png",
    ]),

    new ArrayPictureImpl([
        "ID"                  => "1941",
        "TIMESTAMP_X"         => "11.07.2023 12:04:49",
        "MODULE_ID"           => "iblock",
        "HEIGHT"              => 1000,
        "WIDTH"               => 1000,
        "FILE_SIZE"           => "411873",
        "CONTENT_TYPE"        => "image/png",
        "SUBDIR"              => "iblock/d62",
        "FILE_NAME"           => "fgrr6u69u4znntzj8vg43xnxo4afnn8w.png",
        "ORIGINAL_NAME"       => "full_zacs_07_hpf_a17_n1_in_184394_005_1.png",
        "DESCRIPTION"         => "",
        "HANDLER_ID"          => null,
        "EXTERNAL_ID"         => "0d51db551643baa819ce1ade1d96b466",
        "VERSION_ORIGINAL_ID" => "",
        "META"                => "",
        "SRC"                 => "/upload/iblock/d62/fgrr6u69u4znntzj8vg43xnxo4afnn8w.png",
    ])
];
