<?php

return [
    "SECTIONS" => [
        [
            'ID'                   => '5',
            '~ID'                  => '5',
            'TIMESTAMP_X'          => '17.07.2023 19:53:31',
            '~TIMESTAMP_X'         => '17.07.2023 19:53:31', 'MODIFIED_BY' => '1', '~MODIFIED_BY' => '1',
            'DATE_CREATE'          => '11.07.2023 09:33:10', '~DATE_CREATE' => '11.07.2023 09:33:10',
            'CREATED_BY'           => '1',
            '~CREATED_BY'          => '1', 'IBLOCK_ID' => '10', '~IBLOCK_ID' => '10', 'IBLOCK_SECTION_ID' => null,
            '~IBLOCK_SECTION_ID'   => null, 'ACTIVE' => 'Y', '~ACTIVE' => 'Y', 'GLOBAL_ACTIVE' => 'Y',
            '~GLOBAL_ACTIVE'       => 'Y', 'SORT' => '1', '~SORT' => '1', 'NAME' => 'Настенные сплит-системы',
            '~NAME'                => 'Настенные сплит-системы', 'PICTURE' => [
            'ID'            => '11', 'TIMESTAMP_X' => '17.07.2023 19:53:31', 'MODULE_ID' => 'iblock', 'HEIGHT' => '85',
            'WIDTH'         => '117', 'FILE_SIZE' => '6280', 'CONTENT_TYPE' => 'image/png',
            'SUBDIR'        => 'iblock/0ae/z2annfztdjh9ac7y382co3bn03j6t4o0', 'FILE_NAME' => 'house.png',
            'ORIGINAL_NAME' => 'house.png',
            'HANDLER_ID'    => null,
            'EXTERNAL_ID'   => '58542d7b60580406e0bcd308b8932602', 'VERSION_ORIGINAL_ID' => '', 'META' => '',
            'SRC'           => '/upload/iblock/0ae/z2annfztdjh9ac7y382co3bn03j6t4o0/house.png',
            'UNSAFE_SRC'    => '/upload/iblock/0ae/z2annfztdjh9ac7y382co3bn03j6t4o0/house.png',
            'SAFE_SRC'      => '/upload/iblock/0ae/z2annfztdjh9ac7y382co3bn03j6t4o0/house.png',
            'ALT'           => 'Настенные сплит-системы', 'TITLE' => 'Настенные сплит-системы',
        ], '~PICTURE'              => '11', 'LEFT_MARGIN' => '1', '~LEFT_MARGIN' => '1', 'RIGHT_MARGIN' => '2',
            '~RIGHT_MARGIN'        => '2', 'DEPTH_LEVEL' => '1', '~DEPTH_LEVEL' => '1',
            'DESCRIPTION'          => 'Настенные сплит-системы – это вид кондиционера, который состоит из двух отдельных блоков. Это внутренний блок в виде испарителя и внешний, состоящий из компрессора и конденсатора.

Эти блоки соединяются специальной магистралью. Все шумные комплектующие расположены во внешнем блоке устройства, который вынесен за пределы помещения, поэтому в самой комнате всегда низкий уровень шума. Это главное преимущество такого вида кондиционирования',
            '~DESCRIPTION'         => 'Настенные сплит-системы – это вид кондиционера, который состоит из двух отдельных блоков. Это внутренний блок в виде испарителя и внешний, состоящий из компрессора и конденсатора.

Эти блоки соединяются специальной магистралью. Все шумные комплектующие расположены во внешнем блоке устройства, который вынесен за пределы помещения, поэтому в самой комнате всегда низкий уровень шума. Это главное преимущество такого вида кондиционирования',
            'DESCRIPTION_TYPE'     => 'html', '~DESCRIPTION_TYPE' => 'html',
            'SEARCHABLE_CONTENT'   => 'НАСТЕННЫЕ СПЛИТ-СИСТЕМЫ НАСТЕННЫЕ СПЛИТ-СИСТЕМЫ – ЭТО ВИД КОНДИЦИОНЕРА, КОТОРЫЙ СОСТОИТ ИЗ ДВУХ ОТДЕЛЬНЫХ БЛОКОВ. ЭТО ВНУТРЕННИЙ БЛОК В ВИДЕ ИСПАРИТЕЛЯ И ВНЕШНИЙ, СОСТОЯЩИЙ ИЗ КОМПРЕССОРА И КОНДЕНСАТОРА. ЭТИ БЛОКИ СОЕДИНЯЮТСЯ СПЕЦИАЛЬНОЙ МАГИСТРАЛЬЮ. ВСЕ ШУМНЫЕ КОМПЛЕКТУЮЩИЕ РАСПОЛОЖЕНЫ ВО ВНЕШНЕМ БЛОКЕ УСТРОЙСТВА, КОТОРЫЙ ВЫНЕСЕН ЗА ПРЕДЕЛЫ ПОМЕЩЕНИЯ, ПОЭТОМУ В САМОЙ КОМНАТЕ ВСЕГДА НИЗКИЙ УРОВЕНЬ ШУМА. ЭТО ГЛАВНОЕ ПРЕИМУЩЕСТВО ТАКОГО ВИДА КОНДИЦИОНИРОВАНИЯ',
            '~SEARCHABLE_CONTENT'  => 'НАСТЕННЫЕ СПЛИТ-СИСТЕМЫ НАСТЕННЫЕ СПЛИТ-СИСТЕМЫ – ЭТО ВИД КОНДИЦИОНЕРА, КОТОРЫЙ СОСТОИТ ИЗ ДВУХ ОТДЕЛЬНЫХ БЛОКОВ. ЭТО ВНУТРЕННИЙ БЛОК В ВИДЕ ИСПАРИТЕЛЯ И ВНЕШНИЙ, СОСТОЯЩИЙ ИЗ КОМПРЕССОРА И КОНДЕНСАТОРА. ЭТИ БЛОКИ СОЕДИНЯЮТСЯ СПЕЦИАЛЬНОЙ МАГИСТРАЛЬЮ. ВСЕ ШУМНЫЕ КОМПЛЕКТУЮЩИЕ РАСПОЛОЖЕНЫ ВО ВНЕШНЕМ БЛОКЕ УСТРОЙСТВА, КОТОРЫЙ ВЫНЕСЕН ЗА ПРЕДЕЛЫ ПОМЕЩЕНИЯ, ПОЭТОМУ В САМОЙ КОМНАТЕ ВСЕГДА НИЗКИЙ УРОВЕНЬ ШУМА. ЭТО ГЛАВНОЕ ПРЕИМУЩЕСТВО ТАКОГО ВИДА КОНДИЦИОНИРОВАНИЯ',
            'CODE'                 => 'nastennye-split-sistemy', '~CODE' => 'nastennye-split-sistemy', 'XML_ID' => null,
            '~XML_ID'              => null, 'TMP_ID' => null, '~TMP_ID' => null, 'DETAIL_PICTURE' => null,
            '~DETAIL_PICTURE'      => null, 'SOCNET_GROUP_ID' => null, '~SOCNET_GROUP_ID' => null,
            'LIST_PAGE_URL'        => '/catalog/conditioners/', '~LIST_PAGE_URL' => '/catalog/conditioners/',
            'SECTION_PAGE_URL'     => '/catalog/conditioners/nastennye-split-sistemy/',
            '~SECTION_PAGE_URL'    => '/catalog/conditioners/nastennye-split-sistemy/', 'IBLOCK_TYPE_ID' => 'catalog',
            '~IBLOCK_TYPE_ID'      => 'catalog', 'IBLOCK_CODE' => 'conditioners', '~IBLOCK_CODE' => 'conditioners',
            'IBLOCK_EXTERNAL_ID'   => null, '~IBLOCK_EXTERNAL_ID' => null, 'EXTERNAL_ID' => null,
            '~EXTERNAL_ID'         => null,
            'RELATIVE_DEPTH_LEVEL' => 1,
            'EDIT_LINK'            => '/bitrix/admin/iblock_section_edit.php?IBLOCK_ID=10&type=catalog&ID=5&lang=ru&force_catalog=&filter_section=5&bxpublic=Y&from_module=iblock&return_url=%2Fcatalog%2Fconditioners%2F%3Fclear_cache%3DY',
            'DELETE_LINK'          => '/bitrix/admin/iblock_list_admin.php?IBLOCK_ID=10&type=catalog&lang=ru&action=delete&ID[]=S5&return_url=%2Fcatalog%2Fconditioners%2F%3Fclear_cache%3DY',
            '~ELEMENT_CNT'         => null, 'ELEMENT_CNT' => null, 'ELEMENT_CNT_TITLE' => '', 'IPROPERTY_VALUES' => [],
            'UF_IMAGE'             => '3183',
        ],
        [
            'ID'                   => '3', '~ID' => '3', 'TIMESTAMP_X' => '17.07.2023 19:53:41',
            '~TIMESTAMP_X'         => '17.07.2023 19:53:41', 'MODIFIED_BY' => '1', '~MODIFIED_BY' => '1',
            'DATE_CREATE'          => '10.07.2023 16:26:51', '~DATE_CREATE' => '10.07.2023 16:26:51',
            'CREATED_BY'           => '1',
            '~CREATED_BY'          => '1', 'IBLOCK_ID' => '10', '~IBLOCK_ID' => '10', 'IBLOCK_SECTION_ID' => null,
            '~IBLOCK_SECTION_ID'   => null, 'ACTIVE' => 'Y', '~ACTIVE' => 'Y', 'GLOBAL_ACTIVE' => 'Y',
            '~GLOBAL_ACTIVE'       => 'Y', 'SORT' => '2', '~SORT' => '2', 'NAME' => 'Инверторные сплит-системы',
            '~NAME'                => 'Инверторные сплит-системы', 'PICTURE' => [
            'ID'            => '3164', 'TIMESTAMP_X' => '17.07.2023 19:53:41', 'MODULE_ID' => 'iblock',
            'HEIGHT'        => '81', 'WIDTH' => '98', 'FILE_SIZE' => '11337', 'CONTENT_TYPE' => 'image/png',
            'SUBDIR'        => 'iblock/c5c', 'FILE_NAME' => 'vno3ij6qt59yoi9l4015oan4knrgshhe.png',
            'ORIGINAL_NAME' => 'инверторные.png', 'DESCRIPTION' => '', 'HANDLER_ID' => null,
            'EXTERNAL_ID'   => 'f8e4032f5693c136f120577740f67301', 'VERSION_ORIGINAL_ID' => '', 'META' => '',
            'SRC'           => '/upload/iblock/c5c/vno3ij6qt59yoi9l4015oan4knrgshhe.png',
            'UNSAFE_SRC'    => '/upload/iblock/c5c/vno3ij6qt59yoi9l4015oan4knrgshhe.png',
            'SAFE_SRC'      => '/upload/iblock/c5c/vno3ij6qt59yoi9l4015oan4knrgshhe.png',
            'ALT'           => 'Инверторные сплит-системы', 'TITLE' => 'Инверторные сплит-системы',
        ], '~PICTURE'              => '3164', 'LEFT_MARGIN' => '3', '~LEFT_MARGIN' => '3', 'RIGHT_MARGIN' => '4',
            '~RIGHT_MARGIN'        => '4', 'DEPTH_LEVEL' => '1', '~DEPTH_LEVEL' => '1',
            'DESCRIPTION'          => '',
            '~DESCRIPTION'         => '',
            'DESCRIPTION_TYPE'     => 'html', '~DESCRIPTION_TYPE' => 'html',
            'SEARCHABLE_CONTENT'   => 'ИНВЕРТОРНЫЕ СПЛИТ-СИСТЕМЫ ИНВЕРТОРНАЯ СПЛИТ-СИСТЕМА ЗНАЧИТ КЛИМАТИЧЕСКОЕ ОБОРУДОВАНИЕ С ФУНКЦИЕЙ САМОСТОЯТЕЛЬНОГО РЕГУЛИРОВАНИЯ УРОВНЯ МОЩНОСТИ, В КОТОРОМ ПРОИСХОДИТ ПРЕОБРАЗОВАНИЕ ПЕРИОДИЧЕСКОГО ТОКА РАЗНОЙ ВЕЛИЧИНЫ И НАПРАВЛЕНИЯ В ТОК С НУЖНЫМИ КВАЗИЧАСТИЦАМИ, ВСЛЕДСТВИЕ ЧЕГО ПОВЫШАЕТСЯ ЭФФЕКТИВНОСТЬ ВЫРАБОТКИ УСТРОЙСТВОМ ХОЛОДА И ТЕПЛА. ДАННЫЙ ТИП УСТРОЙСТВА ЯВЛЯЕТСЯ НЕЗАМЕНИМЫМ В РЕГИОНАХ СО ЗНАЧИТЕЛЬНЫМИ ТЕМПЕРАТУРНЫМИ КОЛЕБАНИЯМИ ВО ВНЕШНЕЙ ОКРУЖАЮЩЕЙ СРЕДЕ',
            '~SEARCHABLE_CONTENT'  => 'ИНВЕРТОРНЫЕ СПЛИТ-СИСТЕМЫ ИНВЕРТОРНАЯ СПЛИТ-СИСТЕМА ЗНАЧИТ КЛИМАТИЧЕСКОЕ ОБОРУДОВАНИЕ С ФУНКЦИЕЙ САМОСТОЯТЕЛЬНОГО РЕГУЛИРОВАНИЯ УРОВНЯ МОЩНОСТИ, В КОТОРОМ ПРОИСХОДИТ ПРЕОБРАЗОВАНИЕ ПЕРИОДИЧЕСКОГО ТОКА РАЗНОЙ ВЕЛИЧИНЫ И НАПРАВЛЕНИЯ В ТОК С НУЖНЫМИ КВАЗИЧАСТИЦАМИ, ВСЛЕДСТВИЕ ЧЕГО ПОВЫШАЕТСЯ ЭФФЕКТИВНОСТЬ ВЫРАБОТКИ УСТРОЙСТВОМ ХОЛОДА И ТЕПЛА. ДАННЫЙ ТИП УСТРОЙСТВА ЯВЛЯЕТСЯ НЕЗАМЕНИМЫМ В РЕГИОНАХ СО ЗНАЧИТЕЛЬНЫМИ ТЕМПЕРАТУРНЫМИ КОЛЕБАНИЯМИ ВО ВНЕШНЕЙ ОКРУЖАЮЩЕЙ СРЕДЕ',
            'CODE'                 => 'invertor', '~CODE' => 'invertor', 'XML_ID' => null, '~XML_ID' => null,
            'TMP_ID'               => null, '~TMP_ID' => null, 'DETAIL_PICTURE' => null, '~DETAIL_PICTURE' => null,
            'SOCNET_GROUP_ID'      => null, '~SOCNET_GROUP_ID' => null, 'LIST_PAGE_URL' => '/catalog/conditioners/',
            '~LIST_PAGE_URL'       => '/catalog/conditioners/', 'SECTION_PAGE_URL' => '/catalog/conditioners/invertor/',
            '~SECTION_PAGE_URL'    => '/catalog/conditioners/invertor/', 'IBLOCK_TYPE_ID' => 'catalog',
            '~IBLOCK_TYPE_ID'      => 'catalog', 'IBLOCK_CODE' => 'conditioners', '~IBLOCK_CODE' => 'conditioners',
            'IBLOCK_EXTERNAL_ID'   => null, '~IBLOCK_EXTERNAL_ID' => null, 'EXTERNAL_ID' => null,
            '~EXTERNAL_ID'         => null,
            'RELATIVE_DEPTH_LEVEL' => 1,
            'EDIT_LINK'            => '/bitrix/admin/iblock_section_edit.php?IBLOCK_ID=10&type=catalog&ID=3&lang=ru&force_catalog=&filter_section=3&bxpublic=Y&from_module=iblock&return_url=%2Fcatalog%2Fconditioners%2F%3Fclear_cache%3DY',
            'DELETE_LINK'          => '/bitrix/admin/iblock_list_admin.php?IBLOCK_ID=10&type=catalog&lang=ru&action=delete&ID[]=S3&return_url=%2Fcatalog%2Fconditioners%2F%3Fclear_cache%3DY',
            '~ELEMENT_CNT'         => null, 'ELEMENT_CNT' => null, 'ELEMENT_CNT_TITLE' => '', 'IPROPERTY_VALUES' => [],
            'UF_IMAGE'             => '3179',
        ]
    ]
];
